name: generate podcast feed
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Feed Generator
        run: python feed.py

      - name: Push Changes
        run: |
          git config user.name github-actions
          git config user.email mehmoodasgharch@github.com
          git add .
          git commit -m "Modified feed"
          git push
