---
name: generate podcast feed
on:
  push: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: run feed generator
        uses: mehmoodch/podcast-generator@main
