name: Generate Podcast Feed

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Podcast Generator
        uses: mehmoodch/podcast-generator@main
        with:
          email: ${{ github.actor }}@github.com
          name: ${{ github.actor }}
