name: Generate Podcast Feed

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Podcast Generator
        uses: ./  # This assumes your action.yml is in the root of the repository
        with:
          email: ${{ github.actor }}@example.com
          name: ${{ github.actor }}
